### ISSUE TITLE
MKS Robin Nano (S) v1.3

### ISSUE THREAD

**Issue by nefelim4ag** [makerbase-mks/RepRapFirmware-for-MKS-Boards#7]
Hi, FlyingBear sold Reborn printers with MKS Robin Nano V1.3 or MKS Robin Nano-S V1.3, both with the same controller as Robin Nano V3 (F407) and ESP32 WiFI module, does that possible to install that RRF firmware on that board or do we need to make some modifications?

Thanks!

**Comment by willngton** [comment]
Boards MCU and communication with WIFI module are diffrente, UART vs SPI, also flash memory.
STM32F407VET6（168MHz）	
512KB FLASH/192KB RAM	

STM32F407VGT6（168MHz）
1024KB FLASH/192KB RAM 

Therefore it mostly will not make possible to run RRF  on it.
